apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: jenkins-agent
spec:
  containers:
    - name: simple-agent
      image: registry.k3d.local:5000/jenkins-agent-apictl:4.4
      command:
        - cat
      tty: true

