apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: jenkins-agent
spec:
  containers:
    - name: simple-agent
      image: registry.k3d.local:5000/apictl-ubi9:4.4
      command:
        - cat
      tty: true
    - name: redocly
      image: redocly/cli:latest
      command:
        - cat
      tty: true
